telegram:
  bot:
#    не вписывайте данные, так как можете отправить в публичный репозиторий
#    используйте переменные среды для установки значений
    username: examplebibbobbot #${BOT_NAME}
    token: 8017667179:AAFz90-2nDLU-dXUEdWGhADy8pDevTpM_GQ #${BOT_TOKEN}
    notify:
      frequency:
        value: 2
        unit: MINUTES
      delay:
        value: 3
        unit: MINUTES

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#db:
#  driver:
#    name: org.postgresql.Driver
#  url: jdbc:postgresql://localhost:5432/db
#  user: root
#  password: root
